Reiterated the entire service into proper mvc services
Mikibot/imghoard pull request #1
Opened 2019-09-06 17:13 UTC by velddev

2019-09-07 08:56 UTC, exsersewo approved these changes
lgtm

2019-09-07 17:35 UTC, LovingMelody requested changes
I want to see tests before I can approve it. Otherwise, looks good.

2019-09-07 17:35 UTC, Fuzen-py commented on models/error.go
> +func NewJSON(reason string) atreugo.JSON {
I’d like to see error codes here as well in the future.

2019-09-09 15:44 UTC, Fuzen-py commented
Approving with the promise of tests in the future before production

2019-09-09 15:45 UTC, LovingMelody approved these changes

2019-09-09 15:46 UTC, velddev commented
For now I'll add a todo for tests. The project is too young to properly implement a full test suite in between commits.

One thing I'll work on next is unit tests.

2019-09-09 18:35 UTC, merged